name: test
description: runs dotnet tests with retry
runs:
  using: "composite"
  steps:
    - name: ðŸ” GH_TOKEN
      if: env.GH_TOKEN == ''
      shell: bash
      run: |
        if [ -z "$GH_TOKEN_SECRET" ]
        then
          echo "Using default GITHUB_TOKEN"
          echo "GH_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV
        else
          echo "Using custom GH_TOKEN"
          echo "GH_TOKEN=$GH_TOKEN_SECRET" >> $GITHUB_ENV
        fi

    - name: ðŸ” BOT
      shell: bash
      run: |
        if [ -z "$BOT_NAME"]
        then
          if [ -z "$BOT_NAME_SECRET" ]
          then
            echo "Using default GITHUB_ACTOR as BOT_NAME"
            BOT_NAME="$GITHUB_ACTOR"
          else
            echo "Using custom BOT_NAME"
            BOT_NAME=$BOT_NAME_SECRET
          fi
          echo "BOT_NAME=$BOT_NAME" >> $GITHUB_ENV
        fi

        if [ -z "$BOT_EMAIL"]
        then
          if [ -z "$BOT_EMAIL_SECRET" ]
          then
            echo "Using default GITHUB_EMAIL as BOT_EMAIL"
            BOT_EMAIL="$GITHUB_ACTOR@users.noreply.github.com"
          else
            echo "Using custom BOT_EMAIL"
            BOT_EMAIL="$BOT_EMAIL_SECRET"
          fi
          echo "BOT_EMAIL=$BOT_EMAIL" >> $GITHUB_ENV
        fi

        if [ -z "$BOT_AUTHOR"]
        then
          if [ -z "$BOT_AUTHOR_SECRET" ]
          then
            echo "Using default BOT_NAME <BOT_EMAIL> as BOT_AUTHOR"
            BOT_AUTHOR="$BOT_NAME <$BOT_EMAIL>"
          else
            echo "Using custom BOT_AUTHOR"
            BOT_AUTHOR="$BOT_AUTHOR_SECRET"
          fi
          echo "BOT_AUTHOR=$BOT_AUTHOR" >> $GITHUB_ENV
        fi
